const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const ui={overlay:document.querySelector('#overlay'),title:document.querySelector('#title'),message:document.querySelector('#message'),start:document.querySelector('#start'),score:document.querySelector('#score'),combo:document.querySelector('#combo'),best:document.querySelector('#best'),dash:document.querySelector('#dash'),shield:document.querySelector('#shield'),pause:document.querySelector('#pause'),sound:document.querySelector('#sound')};
let running=false,paused=false,last=0,time=0,score=0,combo=1,spawn=0,starSpawn=0,sound=true,shake=0;
let best=Number(localStorage.getItem('neon-drift-best')||0); ui.best.textContent=String(best).padStart(4,'0');
const player={x:480,y:420,r:11,targetX:480,targetY:420,dash:0,invincible:0,shield:0}; let enemies=[],stars=[],particles=[]; const keys={};
let audio;
function tone(freq,duration=.08,type='sine',volume=.035){if(!sound)return;audio??=new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
function reset(){player.x=player.targetX=canvas.width/2;player.y=player.targetY=canvas.height*.72;player.dash=0;player.invincible=1;player.shield=1;enemies=[];stars=[];particles=[];time=score=spawn=starSpawn=0;combo=1;running=true;paused=false;ui.overlay.classList.add('hidden');ui.pause.classList.remove('show');updateUI();tone(320,.15,'sawtooth')}
function updateUI(){ui.score.textContent=String(Math.floor(score)).padStart(4,'0');ui.combo.textContent='×'+combo;ui.dash.textContent=player.dash<=0?'READY':player.dash.toFixed(1)+'s';ui.shield.textContent=player.shield?'◆':'—'}
function pointer(e){const r=canvas.getBoundingClientRect();player.targetX=(e.clientX-r.left)*canvas.width/r.width;player.targetY=(e.clientY-r.top)*canvas.height/r.height}
function doDash(){if(!running||paused||player.dash>0)return;let dx=player.targetX-player.x,dy=player.targetY-player.y,n=Math.hypot(dx,dy)||1;player.x+=dx/n*130;player.y+=dy/n*130;player.targetX=player.x;player.targetY=player.y;player.dash=2.6;player.invincible=.45;shake=7;burst(player.x,player.y,'#58dfff',20);tone(180,.15,'sawtooth',.06)}
canvas.addEventListener('pointermove',pointer);canvas.addEventListener('pointerdown',e=>{pointer(e);doDash()});ui.start.onclick=reset;ui.sound.onclick=()=>{sound=!sound;ui.sound.textContent='SOUND: '+(sound?'ON':'OFF');tone(500)};
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.code==='Space'){e.preventDefault();doDash()}if(e.key.toLowerCase()==='p'&&running){paused=!paused;ui.pause.classList.toggle('show',paused)}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
function burst(x,y,color,n=12){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=Math.random()*180+40;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:1,color})}}
function collide(a,b,pad=0){return Math.hypot(a.x-b.x,a.y-b.y)<a.r+b.r+pad}
function end(){running=false;shake=18;burst(player.x,player.y,'#ff3cac',30);tone(90,.5,'sawtooth',.08);best=Math.max(best,Math.floor(score));localStorage.setItem('neon-drift-best',best);ui.best.textContent=String(best).padStart(4,'0');ui.title.innerHTML=`${Math.floor(score)}점.<br>한 번 더?`;ui.message.textContent=`별을 모아 콤보를 올리고 더 오래 살아남아 보세요. 최고 기록 ${best}점.`;ui.start.innerHTML='다시 시작 <span>↗</span>';setTimeout(()=>ui.overlay.classList.remove('hidden'),500)}
function update(dt){time+=dt;score+=dt*10*combo;spawn-=dt;starSpawn-=dt;player.dash=Math.max(0,player.dash-dt);player.invincible=Math.max(0,player.invincible-dt);const speed=260+time*7;
  if(spawn<=0){const side=Math.floor(Math.random()*4),r=9+Math.random()*17;let x,y,vx,vy;if(side<2){x=Math.random()*canvas.width;y=side?canvas.height+r:-r;const a=Math.atan2(player.y-y,player.x-x)+(Math.random()-.5)*.5;vx=Math.cos(a)*speed;vy=Math.sin(a)*speed}else{x=side===2?-r:canvas.width+r;y=Math.random()*canvas.height;const a=Math.atan2(player.y-y,player.x-x)+(Math.random()-.5)*.5;vx=Math.cos(a)*speed;vy=Math.sin(a)*speed}enemies.push({x,y,vx,vy,r,rot:0});spawn=Math.max(.18,.8-time*.012)}
  if(starSpawn<=0){stars.push({x:40+Math.random()*(canvas.width-80),y:80+Math.random()*(canvas.height-120),r:8,life:6,pulse:0});starSpawn=1.8+Math.random()*1.5}
  const k=330;if(keys.w||keys.arrowup)player.targetY-=k*dt;if(keys.s||keys.arrowdown)player.targetY+=k*dt;if(keys.a||keys.arrowleft)player.targetX-=k*dt;if(keys.d||keys.arrowright)player.targetX+=k*dt;player.x+=(player.targetX-player.x)*Math.min(1,dt*10);player.y+=(player.targetY-player.y)*Math.min(1,dt*10);player.x=Math.max(18,Math.min(canvas.width-18,player.x));player.y=Math.max(55,Math.min(canvas.height-18,player.y));
  enemies.forEach(e=>{e.x+=e.vx*dt;e.y+=e.vy*dt;e.rot+=dt*3;if(!e.near&&!collide(player,e)&&collide(player,e,25)){e.near=true;score+=25*combo;tone(760,.04)}});enemies=enemies.filter(e=>e.x>-80&&e.x<canvas.width+80&&e.y>-80&&e.y<canvas.height+80);if(player.invincible<=0&&enemies.some(e=>collide(player,e))){if(player.shield){player.shield=0;player.invincible=1.2;shake=14;burst(player.x,player.y,'#58dfff',25);enemies=enemies.filter(e=>Math.hypot(player.x-e.x,player.y-e.y)>150);tone(120,.3,'square',.07)}else{end();return}}
  stars.forEach(s=>{s.life-=dt;s.pulse+=dt*5;if(collide(player,s)){s.life=0;combo=Math.min(9,combo+1);score+=50*combo;burst(s.x,s.y,'#caff47');tone(440+combo*55,.1,'square')}});stars=stars.filter(s=>s.life>0);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.97;p.vy*=.97;p.life-=dt*1.7});particles=particles.filter(p=>p.life>0);updateUI()}
function draw(){ctx.save();if(shake>0){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.88}ctx.fillStyle='#070a10';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='rgba(90,120,150,.09)';ctx.lineWidth=1;const off=(time*35)%60;for(let x=-60+off;x<canvas.width;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke()}for(let y=-60+off;y<canvas.height;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}
  stars.forEach(s=>{ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.pulse);ctx.shadowBlur=24;ctx.shadowColor='#caff47';ctx.fillStyle='#caff47';for(let i=0;i<4;i++){ctx.rotate(Math.PI/2);ctx.fillRect(-2,-13,4,26)}ctx.restore()});
  enemies.forEach(e=>{ctx.save();ctx.translate(e.x,e.y);ctx.rotate(e.rot);ctx.shadowBlur=18;ctx.shadowColor='#ff3cac';ctx.strokeStyle='#ff3cac';ctx.lineWidth=3;ctx.strokeRect(-e.r,-e.r,e.r*2,e.r*2);ctx.restore()});
  particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.fillRect(p.x-2,p.y-2,4,4)});ctx.globalAlpha=1;ctx.save();ctx.translate(player.x,player.y);ctx.shadowBlur=28;ctx.shadowColor='#58dfff';ctx.fillStyle='#eafaff';ctx.beginPath();ctx.moveTo(0,-15);ctx.lineTo(11,12);ctx.lineTo(0,7);ctx.lineTo(-11,12);ctx.closePath();ctx.fill();ctx.restore();ctx.restore()}
function loop(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;if(running&&!paused)update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
